SELECT
    UGU.USER_ID,
    UGU.NICKNAME,
    SUM(UGB.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD UGB
JOIN
    USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE
    UGB.STATUS = 'DONE'
    AND UGB.CREATED_DATE <= CURRENT_DATE
GROUP BY
    UGU.USER_ID, UGU.NICKNAME
HAVING
    SUM(UGB.PRICE) >= 700000
ORDER BY
    TOTAL_SALES ASC;
